### ISSUE TITLE
Missing Dependency to hibernate

### ISSUE THREAD

**Issue by falco467** [roskart/dropwizard-jaxws#10]
Hi!

If I use v. 1.0.0 in a Maven project as a dependency, I get an error in Eclipse:
`The type org.hibernate.SessionFactory cannot be resolved. It is indirectly referenced from required .class files`

If I add hibernate-core as a manual dependency the error is resolved.

**Comment by roskart** [comment]
Thank you for your contribution and sorry for the delay.

Hibernate dependency is not missing. This issue occurs because dropwizard-hibernate dependency in dropwizard-jaxws uses `provided` scope. This enables more control over deployment when using the library.

As far as I can tell, only Eclipse/M2E is affected by this. I could not reproduce this issue when building and running application from command line or when using IntelliJ Idea.

I propose that Dropwizard dependencies in dropwizard-jaxws continue to use `provided` scope. Users that run into this issue can change the scope of dropwizard-hibernate dependency in their project to `compile` when not using Hibernate:

```
        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-hibernate</artifactId>
            <version>1.0.0</version>
            <scope>compile</scope>
        </dependency>
```

Hibernate-core dependency does not have to be declared.
