### ISSUE TITLE
How do i enable this for HTTPS.

### ISSUE THREAD

**Issue by Sandeepgonthkar** [roskart/dropwizard-jaxws#26]
Hi, 
we are using this in one of our  dropwizard services and it works well in local (http).
how do add https support. Currently this returns 403 on https (servers).

**Comment by roskart** [comment]
The transport being used does not impact behavior of dropwizard-jaxws. You did not provide any information on what are you trying to achieve, or which versions of dropwizard-jaxws you are using.

Regarding HTTP status 403 - there was an issue #20 which incorrectly returned 403 in case of authentication error (bad credentials). This issue was fixed in 2019 and has nothing to do with HTTPS/SSL.

I just tried and SSL works out of the box using vanilla Dropwizard configuration:
https://www.dropwizard.io/en/latest/manual/core.html#ssl

**Comment by roskart** [comment]
I'm closing this issue as it does not seem to be an error in dropwizard-jaxws. Feel free to reopen this ticket if there is any new information.
